theme: minima
plugins:
  - jekyll-relative-links
  - jekyll-github-metadata
  - jemoji

relative_links:
  enabled: true
  collections: true

title: "Bluetooth Volume Manager"
description: "An Android app that automates Bluetooth device specific actions such as volume adjustments."
author: "by Matthias Urhahn"

include:
  - PRIVACY_POLICY.md
  - CHANGELOG.md
exclude:
  - buildSrc
  - gradle/wrapper
  - fastlane
  - Gemfile
  - Gemfile.lock
  - crowdin*
  - app
  - CLAUDE.md
