name: Code tests & eval

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint-vital:
    name: Lint vitals
    strategy:
      fail-fast: false
      matrix:
        variant: [ Beta,Release ]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - name: Setup project and build environment
        uses: ./.github/actions/common-setup

      - name: Check for fatal lint issues
        run: ./gradlew lintVital${{ matrix.variant }}

  build-modules:
    name: Build apps
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - name: Setup project and build environment
        uses: ./.github/actions/common-setup

      - name: Build modules
        run: ./gradlew assembleDebug

  test-modules:
    name: Unit tests
    strategy:
      fail-fast: false
      matrix:
        variant: [ Debug,Beta,Release ]
        flavor: [ test ]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - name: Setup project and build environment
        uses: ./.github/actions/common-setup

      - name: Test modules
        run: ./gradlew ${{ matrix.flavor }}${{ matrix.variant }}UnitTest